apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: connor
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: connor
  replicas: 2 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: connor
    spec:
      containers:
      - name: connor
        image: docker.io/talhaabdurrahman/env-tester
        ports:
        - containerPort: 8500
        imagePullPolicy: Always 