apiVersion: v1
kind: Service
metadata:
  name: connor
  labels:
    app: connor
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8500
  selector:
    app: connor
  type: LoadBalancer